apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: k8s-dev
type: Opaque
stringData:
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: password
  STAFF_JWT_SECRET: super-secret-jwt-key