apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: k8s-dev
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "gke-standard-ingress-ip"
spec:
  rules:
    http:
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service:
              name: api
              port:
                number: 3000
