steps:
  # Build API Gateway image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - ./lab-6-gke-standard/backend/docker/Dockerfile.api
      - -t
      - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA
      - ./lab-6-gke-standard/backend

  # Push API Gateway image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA

images:
  - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA

timeout: 1200s # 20 minutes

options:
  logging: CLOUD_LOGGING_ONLY
