steps:
  # Build Auth MS image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - ./lab-6-gke-standard/backend/docker/Dockerfile.auth
      - -t
      - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/auth-ms:$COMMIT_SHA
      - ./lab-6-gke-standard/backend

  # Push Auth MS image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/auth-ms:$COMMIT_SHA

  # Deploy Auth MS to GKE cluster
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/auth
      - auth=$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/auth-ms:$COMMIT_SHA
      - --namespace=k8s-dev
    env:
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
      - CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE

images:
  - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/auth-ms:$COMMIT_SHA

timeout: 1200s # 20 minutes

options:
  logging: CLOUD_LOGGING_ONLY
