apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: k8s-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: REGION-docker.pkg.dev/PROJECT_ID/backend/auth-ms:TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          command:
            - sh
            - -c
            - npx prisma migrate deploy --schema=databases/auth/schema.prisma && node dist/apps/auth/main

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          env:
            # =========================
            # DB CONFIG (from config + secret)
            # =========================
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_HOST

            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_PORT

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_DATABASE

            # =========================
            # SERVICE COMMUNICATION
            # =========================
            - name: AUTH_MS_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: AUTH_MS_URL

            # =========================
            # OPTIONAL: build DSN in app or here
            # =========================
            - name: AUTH_MS_DATABASE_URL
              value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DATABASE)"

            # =========================
            # ENVIRONMENT
            # =========================
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: NODE_ENV
