steps:
  # Build API Gateway image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - ./lab-7-gke-autopilot/backend/docker/Dockerfile.api
      - -t
      - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA
      - ./lab-7-gke-autopilot/backend

  # Push API Gateway image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA

  # Deploy API Gateway to GKE cluster
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/api
      - api=$_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA
      - --namespace=k8s-dev
    env:
      - CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME
      - CLOUDSDK_COMPUTE_ZONE=$_CLUSTER_ZONE

images:
  - $_REGION-docker.pkg.dev/$_PROJECT_ID/backend/api-gateway:$COMMIT_SHA

timeout: 1200s # 20 minutes

options:
  logging: CLOUD_LOGGING_ONLY
