apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: k8s-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0-debian
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MYSQL_DATABASE
          args:
            - --default-authentication-plugin=mysql_native_password

          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      restartPolicy: Always